local border = require('utils.ui').get_border()
require('which-key').setup({
	preset = 'helix',
	win = {
		border = border,
	},
	icons = {
		mappings = false,
		breadcrumb = '',
		separator = ' ',
		group = '',
		keys = {
			Up = '^',
			Down = 'v',
			Left = '<',
			Right = '>',
			C = '[C]',
			M = '[M]',
			D = '[D]',
			S = '[S]',
			CR = '[Enter]',
			Esc = '[Esc]',
			ScrollWheelDown = 'v~',
			ScrollWheelUp = '^~',
			NL = '[Enter]',
			BS = '[BS]',
			Space = '[ ]',
			Tab = '[Tab]',
			F1 = 'F1',
			F2 = 'F2',
			F3 = 'F3',
			F4 = 'F4',
			F5 = 'F5',
			F6 = 'F6',
			F7 = 'F7',
			F8 = 'F8',
			F9 = 'F9',
			F10 = 'F10',
			F11 = 'F11',
			F12 = 'F12',
		},
	},
})
