local o = vim.opt

o.number = true
o.relativenumber = true
o.tabstop = 4
o.shiftwidth = 4
o.expandtab = true
o.smartindent = true
o.signcolumn = 'yes'
o.swapfile = false
o.undofile = true
o.clipboard = 'unnamedplus'
o.termguicolors = true
o.wrap = false
o.scrolloff = 8
o.updatetime = 250
o.laststatus = 3
o.cmdheight = 0
o.winborder = 'single'
o.viewoptions = 'cursor,folds'
